version: "3"
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/pg-volume:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - 5432:5432
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NEW_RELIC_APP_NAME=ENROLLMENT_LOCAL
      - NODE_ENV=development
      - SOURCECRED_CACHE_DB_PATH=/instance/cache/sourcecred/github
    env_file:
      - .env
    ports:
      - 8080:8080
  # web:
  #   build: .
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 8080:3000
  #   depends_on:
  #     - db
