import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navigation/navbar";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import { NextAuthProvider } from "./nextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options);

  return (
    <NextAuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <nav>
            <Navbar session={session}></Navbar>
          </nav>
          {children}
        </body>
      </html>
    </NextAuthProvider>
  );
}
