name: Deploy migrations
on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn install

      - name: Apply all pending migrations to the database
        run: yarn prisma migrate deploy
        env:
          FRONTEND_DATABASE_URL: ${{ secrets.DATABASE_URL }}
